-- =========================================================================
-- STORED PROCEDURES CREATION SCRIPT - QLDSV_HTC
-- Target: SQL Server
-- Description: Creates all Stored Procedures required by the Web Application,
--              tailored to match your exact database tables and columns.
-- =========================================================================

USE [QLDSV_HTC];
GO
-- =========================================================================
-- SUPPORTING INDEXES FOR COMMON FILTERS / JOINS
-- =========================================================================

IF OBJECT_ID('dbo.IX_SINHVIEN_MALOP', 'IX') IS NULL
BEGIN
    CREATE INDEX IX_SINHVIEN_MALOP
    ON dbo.SINHVIEN (MALOP)
    INCLUDE (MASV, HO, TEN, PHAI, NGAYSINH, DIACHI, DANGHIHOC);
END;
GO



IF OBJECT_ID('dbo.IX_LOP_MAKHOA', 'IX') IS NULL
BEGIN
    CREATE INDEX IX_LOP_MAKHOA
    ON dbo.LOP (MAKHOA)
    INCLUDE (MALOP, TENLOP, KHOAHOC);
END;
GO



IF OBJECT_ID('dbo.IX_DANGKY_MASV', 'IX') IS NULL
BEGIN
    CREATE INDEX IX_DANGKY_MASV
    ON dbo.DANGKY (MASV)
    INCLUDE (MALTC, DIEM_CC, DIEM_GK, DIEM_CK, HUYDANGKY);
END;
GO

IF OBJECT_ID('dbo.IX_DANGKY_MALTC_HUYDANGKY', 'IX') IS NULL
BEGIN
    -- Index lọc HUYDANGKY=0 theo MALTC - giúp các SP lọc đăng ký active seek nhanh
    CREATE INDEX IX_DANGKY_MALTC_HUYDANGKY
    ON dbo.DANGKY (MALTC, HUYDANGKY)
    INCLUDE (MASV, DIEM_CC, DIEM_GK, DIEM_CK);
END;
GO

IF OBJECT_ID('dbo.IX_DANGKY_MALTC_SI_SO', 'IX') IS NULL
BEGIN
    CREATE INDEX IX_DANGKY_MALTC_SI_SO
    ON dbo.DANGKY (MALTC)
    INCLUDE (MASV)
    WHERE HUYDANGKY = 0; -- Ngắn gọn, chuẩn cú pháp Filtered Index
END;
GO

IF OBJECT_ID('dbo.IX_LOPTINCHI_MAKHOA', 'IX') IS NULL
BEGIN
    CREATE INDEX IX_LOPTINCHI_MAKHOA
    ON dbo.LOPTINCHI (MAKHOA)
    INCLUDE (MALTC, NIENKHOA, HOCKY, MAMH, NHOM, MAGV, SOSVTOITHIEU, HUYLOP);
END;
GO

IF OBJECT_ID('dbo.IX_LOPTINCHI_MAGV', 'IX') IS NULL
BEGIN
    CREATE INDEX IX_LOPTINCHI_MAGV
    ON dbo.LOPTINCHI (MAGV)
    INCLUDE (MALTC, NIENKHOA, HOCKY, MAMH, NHOM, MAKHOA, SOSVTOITHIEU, HUYLOP);
END;
GO

IF OBJECT_ID('dbo.IX_LOPTINCHI_NIENKHOA_HOCKY', 'IX') IS NULL
BEGIN
    CREATE INDEX IX_LOPTINCHI_NIENKHOA_HOCKY
    ON dbo.LOPTINCHI (NIENKHOA, HOCKY)
    INCLUDE (MALTC, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP);
END;
GO

IF OBJECT_ID('dbo.IX_GIANGVIEN_MAKHOA', 'IX') IS NULL
BEGIN
    CREATE INDEX IX_GIANGVIEN_MAKHOA
    ON dbo.GIANGVIEN (MAKHOA)
    INCLUDE (MAGV, HO, TEN, HOCVI, HOCHAM, CHUYENMON);
END;
GO-- =========================================================================
-- 1. STORED PROCEDURES - KHOA
-- =========================================================================

CREATE OR ALTER PROCEDURE SP_GET_ALL_KHOA
AS
BEGIN
    SELECT MAKHOA, TENKHOA 
    FROM KHOA;
END;
GO

CREATE OR ALTER PROCEDURE SP_GET_KHOA_BY_ID
    @MAKHOA NCHAR(10)
AS
BEGIN
    SELECT MAKHOA, TENKHOA 
    FROM KHOA 
    WHERE MAKHOA = @MAKHOA;
END;
GO

CREATE OR ALTER PROCEDURE SP_CREATE_KHOA
    @MAKHOA NCHAR(10),
    @TENKHOA NVARCHAR(50)
AS
BEGIN
    INSERT INTO KHOA (MAKHOA, TENKHOA)
    VALUES (@MAKHOA, @TENKHOA);
END;
GO

CREATE OR ALTER PROCEDURE SP_UPDATE_KHOA
    @MAKHOA NCHAR(10),
    @TENKHOA NVARCHAR(50)
AS
BEGIN
    UPDATE KHOA
    SET TENKHOA = @TENKHOA
    WHERE MAKHOA = @MAKHOA;
END;
GO

CREATE OR ALTER PROCEDURE SP_DELETE_KHOA
    @MAKHOA NCHAR(10)
AS
BEGIN
    DELETE FROM KHOA
    WHERE MAKHOA = @MAKHOA;
END;
GO

CREATE OR ALTER PROCEDURE SP_RESTORE_KHOA
    @MAKHOA NCHAR(10)
AS
BEGIN
    -- No-op: KHOA table doesn't have Daxoa in your schema
    SELECT 1;
END;
GO

CREATE OR ALTER PROCEDURE SP_SEARCH_KHOA
    @KEYWORD NVARCHAR(100)
AS
BEGIN
    SELECT MAKHOA, TENKHOA
    FROM KHOA
    WHERE MAKHOA LIKE '%' + @KEYWORD + '%' OR TENKHOA LIKE '%' + @KEYWORD + '%';
END;
GO


-- =========================================================================
-- 2. STORED PROCEDURES - LOP
-- =========================================================================

CREATE OR ALTER PROCEDURE SP_GET_ALL_LOP
AS
BEGIN
    SELECT MALOP, TENLOP, KHOAHOC, MAKHOA
    FROM LOP;
END;
GO

CREATE OR ALTER PROCEDURE SP_GET_LOP_BY_ID
    @MALOP NCHAR(10)
AS
BEGIN
    SELECT MALOP, TENLOP, KHOAHOC, MAKHOA
    FROM LOP
    WHERE MALOP = @MALOP;
END;
GO

CREATE OR ALTER PROCEDURE SP_GET_LOP_BY_KHOA
    @MAKHOA NCHAR(10)
AS
BEGIN
    SELECT MALOP, TENLOP, KHOAHOC, MAKHOA
    FROM LOP
    WHERE MAKHOA = @MAKHOA;
END;
GO

CREATE OR ALTER PROCEDURE SP_CREATE_LOP
    @MALOP NCHAR(10),
    @TENLOP NVARCHAR(50),
    @KHOAHOC NCHAR(9),
    @MAKHOA NCHAR(10)
AS
BEGIN
    INSERT INTO LOP (MALOP, TENLOP, KHOAHOC, MAKHOA)
    VALUES (@MALOP, @TENLOP, @KHOAHOC, @MAKHOA);
END;
GO

CREATE OR ALTER PROCEDURE SP_UPDATE_LOP
    @MALOP NCHAR(10),
    @TENLOP NVARCHAR(50),
    @KHOAHOC NCHAR(9),
    @MAKHOA NCHAR(10)
AS
BEGIN
    UPDATE LOP
    SET TENLOP = @TENLOP,
        KHOAHOC = @KHOAHOC,
        MAKHOA = @MAKHOA
    WHERE MALOP = @MALOP;
END;
GO

CREATE OR ALTER PROCEDURE SP_DELETE_LOP
    @MALOP NCHAR(10)
AS
BEGIN
    DELETE FROM LOP
    WHERE MALOP = @MALOP;
END;
GO

CREATE OR ALTER PROCEDURE SP_RESTORE_LOP
    @MALOP NCHAR(10)
AS
BEGIN
    -- No-op
    SELECT 1;
END;
GO

CREATE OR ALTER PROCEDURE SP_SEARCH_LOP
    @KEYWORD NVARCHAR(100)
AS
BEGIN
    SELECT MALOP, TENLOP, KHOAHOC, MAKHOA
    FROM LOP
    WHERE MALOP LIKE '%' + @KEYWORD + '%' OR TENLOP LIKE '%' + @KEYWORD + '%';
END;
GO


-- =========================================================================
-- 3. STORED PROCEDURES - SINHVIEN
-- =========================================================================

CREATE OR ALTER PROCEDURE SP_GET_ALL_SINHVIEN
AS
BEGIN
    SELECT MASV, HO, TEN, MALOP, PHAI, NGAYSINH, DIACHI, DANGHIHOC
    FROM SINHVIEN;
END;
GO

CREATE OR ALTER PROCEDURE SP_GET_SINHVIEN_BY_ID
    @MASV NCHAR(10)
AS
BEGIN
    SELECT MASV, HO, TEN, MALOP, PHAI, NGAYSINH, DIACHI, DANGHIHOC
    FROM SINHVIEN
    WHERE MASV = @MASV;
END;
GO

CREATE OR ALTER PROCEDURE SP_GET_SINHVIEN_BY_LOP
    @MALOP NCHAR(10)
AS
BEGIN
    SELECT MASV, HO, TEN, MALOP, PHAI, NGAYSINH, DIACHI, DANGHIHOC
    FROM SINHVIEN
    WHERE MALOP = @MALOP;
END;
GO

CREATE OR ALTER PROCEDURE SP_GET_SINHVIEN_BY_KHOA
    @MAKHOA NCHAR(10)
AS
BEGIN
    SELECT sv.MASV, sv.HO, sv.TEN, sv.MALOP, sv.PHAI, sv.NGAYSINH, sv.DIACHI, sv.DANGHIHOC
    FROM SINHVIEN sv
    INNER JOIN LOP l ON sv.MALOP = l.MALOP
    WHERE l.MAKHOA = @MAKHOA;
END;
GO

CREATE OR ALTER PROCEDURE SP_CREATE_SINHVIEN
    @MASV NCHAR(10),
    @HO NVARCHAR(50),
    @TEN NVARCHAR(10),
    @MALOP NCHAR(10),
    @PHAI BIT,
    @NGAYSINH DATE = NULL,
    @DIACHI NVARCHAR(100) = NULL,
    @DANGHIHOC BIT = 0
AS
BEGIN
    INSERT INTO SINHVIEN (MASV, HO, TEN, MALOP, PHAI, NGAYSINH, DIACHI, DANGHIHOC)
    VALUES (@MASV, @HO, @TEN, @MALOP, @PHAI, @NGAYSINH, @DIACHI, @DANGHIHOC);
END;
GO

CREATE OR ALTER PROCEDURE SP_UPDATE_SINHVIEN
    @MASV NCHAR(10),
    @HO NVARCHAR(50),
    @TEN NVARCHAR(10),
    @MALOP NCHAR(10),
    @PHAI BIT,
    @NGAYSINH DATE = NULL,
    @DIACHI NVARCHAR(100) = NULL,
    @DANGHIHOC BIT = 0
AS
BEGIN
    UPDATE SINHVIEN
    SET HO = @HO,
        TEN = @TEN,
        MALOP = @MALOP,
        PHAI = @PHAI,
        NGAYSINH = @NGAYSINH,
        DIACHI = @DIACHI,
        DANGHIHOC = @DANGHIHOC
    WHERE MASV = @MASV;
END;
GO

CREATE OR ALTER PROCEDURE SP_DELETE_SINHVIEN
    @MASV NCHAR(10)
AS
BEGIN
    DELETE FROM SINHVIEN
    WHERE MASV = @MASV;
END;
GO

CREATE OR ALTER PROCEDURE SP_RESTORE_SINHVIEN
    @MASV NCHAR(10)
AS
BEGIN
    UPDATE SINHVIEN
    SET DANGHIHOC = 0
    WHERE MASV = @MASV;
END;
GO

CREATE OR ALTER PROCEDURE SP_SEARCH_SINHVIEN
    @KEYWORD NVARCHAR(100)
AS
BEGIN
    SELECT MASV, HO, TEN, MALOP, PHAI, NGAYSINH, DIACHI, DANGHIHOC
    FROM SINHVIEN
    WHERE MASV LIKE '%' + @KEYWORD + '%' 
       OR HO LIKE '%' + @KEYWORD + '%' 
       OR TEN LIKE '%' + @KEYWORD + '%' 
       OR HO + ' ' + TEN LIKE '%' + @KEYWORD + '%';
END;
GO

CREATE OR ALTER PROCEDURE SP_UPDATE_SINHVIEN_STATUS
    @MASV NCHAR(10),
    @DANGHIHOC BIT
AS
BEGIN
    UPDATE SINHVIEN
    SET DANGHIHOC = @DANGHIHOC
    WHERE MASV = @MASV;
END;
GO


-- =========================================================================
-- 4. STORED PROCEDURES - GIANGVIEN
-- =========================================================================

CREATE OR ALTER PROCEDURE SP_GET_ALL_GIANGVIEN
AS
BEGIN
    SELECT MAGV, MAKHOA, HO, TEN, HOCVI, HOCHAM, CHUYENMON
    FROM GIANGVIEN;
END;
GO

CREATE OR ALTER PROCEDURE SP_GET_GIANGVIEN_BY_ID
    @MAGV NCHAR(10)
AS
BEGIN
    SELECT MAGV, MAKHOA, HO, TEN, HOCVI, HOCHAM, CHUYENMON
    FROM GIANGVIEN
    WHERE MAGV = @MAGV;
END;
GO

CREATE OR ALTER PROCEDURE SP_GET_GIANGVIEN_BY_KHOA
    @MAKHOA NCHAR(10)
AS
BEGIN
    SELECT MAGV, MAKHOA, HO, TEN, HOCVI, HOCHAM, CHUYENMON
    FROM GIANGVIEN
    WHERE MAKHOA = @MAKHOA;
END;
GO

CREATE OR ALTER PROCEDURE SP_CREATE_GIANGVIEN
    @MAGV NCHAR(10),
    @MAKHOA NCHAR(10),
    @HO NVARCHAR(50),
    @TEN NVARCHAR(10),
    @HOCVI NVARCHAR(20),
    @HOCHAM NVARCHAR(20),
    @CHUYENMON NVARCHAR(50)
AS
BEGIN
    INSERT INTO GIANGVIEN (MAGV, MAKHOA, HO, TEN, HOCVI, HOCHAM, CHUYENMON)
    VALUES (@MAGV, @MAKHOA, @HO, @TEN, @HOCVI, @HOCHAM, @CHUYENMON);
END;
GO

CREATE OR ALTER PROCEDURE SP_UPDATE_GIANGVIEN
    @MAGV NCHAR(10),
    @MAKHOA NCHAR(10),
    @HO NVARCHAR(50),
    @TEN NVARCHAR(10),
    @HOCVI NVARCHAR(20),
    @HOCHAM NVARCHAR(20),
    @CHUYENMON NVARCHAR(50)
AS
BEGIN
    UPDATE GIANGVIEN
    SET MAKHOA = @MAKHOA,
        HO = @HO,
        TEN = @TEN,
        HOCVI = @HOCVI,
        HOCHAM = @HOCHAM,
        CHUYENMON = @CHUYENMON
    WHERE MAGV = @MAGV;
END;
GO

CREATE OR ALTER PROCEDURE SP_DELETE_GIANGVIEN
    @MAGV NCHAR(10)
AS
BEGIN
    DELETE FROM GIANGVIEN
    WHERE MAGV = @MAGV;
END;
GO

CREATE OR ALTER PROCEDURE SP_RESTORE_GIANGVIEN
    @MAGV NCHAR(10)
AS
BEGIN
    -- No-op
    SELECT 1;
END;
GO

CREATE OR ALTER PROCEDURE SP_SEARCH_GIANGVIEN
    @KEYWORD NVARCHAR(100)
AS
BEGIN
    SELECT MAGV, MAKHOA, HO, TEN, HOCVI, HOCHAM, CHUYENMON
    FROM GIANGVIEN
    WHERE MAGV LIKE '%' + @KEYWORD + '%' 
       OR HO LIKE '%' + @KEYWORD + '%' 
       OR TEN LIKE '%' + @KEYWORD + '%' 
       OR HO + ' ' + TEN LIKE '%' + @KEYWORD + '%';
END;
GO


-- =========================================================================
-- 5. STORED PROCEDURES - MONHOC
-- =========================================================================

CREATE OR ALTER PROCEDURE SP_GET_ALL_MONHOC
AS
BEGIN
    SELECT MAMH, TENMH, SOTIET_LT, SOTIET_TH
    FROM MONHOC;
END;
GO

CREATE OR ALTER PROCEDURE SP_GET_MONHOC_BY_ID
    @MAMH NCHAR(10)
AS
BEGIN
    SELECT MAMH, TENMH, SOTIET_LT, SOTIET_TH
    FROM MONHOC
    WHERE MAMH = @MAMH;
END;
GO

CREATE OR ALTER PROCEDURE SP_CREATE_MONHOC
    @MAMH NCHAR(10),
    @TENMH NVARCHAR(50),
    @SOTIET_LT INT,
    @SOTIET_TH INT
AS
BEGIN
    INSERT INTO MONHOC (MAMH, TENMH, SOTIET_LT, SOTIET_TH)
    VALUES (@MAMH, @TENMH, @SOTIET_LT, @SOTIET_TH);
END;
GO

CREATE OR ALTER PROCEDURE SP_UPDATE_MONHOC
    @MAMH NCHAR(10),
    @TENMH NVARCHAR(50),
    @SOTIET_LT INT,
    @SOTIET_TH INT
AS
BEGIN
    UPDATE MONHOC
    SET TENMH = @TENMH,
        SOTIET_LT = @SOTIET_LT,
        SOTIET_TH = @SOTIET_TH
    WHERE MAMH = @MAMH;
END;
GO

CREATE OR ALTER PROCEDURE SP_DELETE_MONHOC
    @MAMH NCHAR(10)
AS
BEGIN
    DELETE FROM MONHOC
    WHERE MAMH = @MAMH;
END;
GO

CREATE OR ALTER PROCEDURE SP_RESTORE_MONHOC
    @MAMH NCHAR(10)
AS
BEGIN
    -- No-op
    SELECT 1;
END;
GO

CREATE OR ALTER PROCEDURE SP_SEARCH_MONHOC
    @KEYWORD NVARCHAR(100)
AS
BEGIN
    SELECT MAMH, TENMH, SOTIET_LT, SOTIET_TH
    FROM MONHOC
    WHERE MAMH LIKE '%' + @KEYWORD + '%' OR TENMH LIKE '%' + @KEYWORD + '%';
END;
GO


-- =========================================================================
-- 6. STORED PROCEDURES - LOPTINCHI
-- =========================================================================

CREATE OR ALTER PROCEDURE SP_GET_ALL_LOPTINCHI
AS
BEGIN
    SELECT 
        ltc.MALTC, 
        ltc.NIENKHOA, 
        ltc.HOCKY, 
        ltc.MAMH, 
        mh.TENMH,
        ltc.NHOM, 
        ltc.MAGV, 
        gv.HO + ' ' + gv.TEN AS TENGV,
        ltc.MAKHOA, 
        ltc.SOSVTOITHIEU, 
        ltc.HUYLOP
    FROM LOPTINCHI ltc
    INNER JOIN MONHOC mh ON ltc.MAMH = mh.MAMH
    INNER JOIN GIANGVIEN gv ON ltc.MAGV = gv.MAGV
    ORDER BY ltc.MALTC DESC;
END;
GO

CREATE OR ALTER PROCEDURE SP_GET_LOPTINCHI_BY_ID
    @MALTC INT
AS
BEGIN
    SELECT MALTC, NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP
    FROM LOPTINCHI
    WHERE MALTC = @MALTC;
END;
GO

CREATE OR ALTER PROCEDURE SP_GET_LOPTINCHI_BY_KHOA
    @MAKHOA NCHAR(10)
AS
BEGIN
    SELECT MALTC, NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP
    FROM LOPTINCHI
    WHERE MAKHOA = @MAKHOA;
END;
GO

CREATE OR ALTER PROCEDURE SP_GET_LOPTINCHI_BY_NIENKHOA_HOCKY
    @NIENKHOA NCHAR(9),
    @HOCKY INT
AS
BEGIN
    SELECT 
        ltc.MALTC, 
        ltc.NIENKHOA, 
        ltc.HOCKY, 
        ltc.MAMH, 
        mh.TENMH,
        ltc.NHOM, 
        ltc.MAGV, 
        gv.HO + ' ' + gv.TEN AS TENGV,
        ltc.MAKHOA, 
        ltc.SOSVTOITHIEU, 
        ltc.HUYLOP
    FROM LOPTINCHI ltc
    INNER JOIN MONHOC mh ON ltc.MAMH = mh.MAMH
    INNER JOIN GIANGVIEN gv ON ltc.MAGV = gv.MAGV
    WHERE ltc.NIENKHOA = @NIENKHOA 
      AND ltc.HOCKY = @HOCKY
      AND ltc.HUYLOP = 0;
END;
GO

CREATE OR ALTER PROCEDURE SP_GET_LOPTINCHI_BY_GIANGVIEN
    @MAGV NCHAR(10)
AS
BEGIN
    SELECT MALTC, NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP
    FROM LOPTINCHI
    WHERE MAGV = @MAGV;
END;
GO

CREATE OR ALTER PROCEDURE SP_CREATE_LOPTINCHI
    @NIENKHOA NCHAR(9),
    @HOCKY INT,
    @MAMH NCHAR(10),
    @NHOM INT,
    @MAGV NCHAR(10),
    @MAKHOA NCHAR(10),
    @SOSVTOITHIEU INT,
    @HUYLOP BIT
AS
BEGIN
    INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP)
    VALUES (@NIENKHOA, @HOCKY, @MAMH, @NHOM, @MAGV, @MAKHOA, @SOSVTOITHIEU, @HUYLOP);
END;
GO

CREATE OR ALTER PROCEDURE SP_UPDATE_LOPTINCHI
    @MALTC INT,
    @NIENKHOA NCHAR(9),
    @HOCKY INT,
    @MAMH NCHAR(10),
    @NHOM INT,
    @MAGV NCHAR(10),
    @MAKHOA NCHAR(10),
    @SOSVTOITHIEU INT
AS
BEGIN
    UPDATE LOPTINCHI
    SET NIENKHOA = @NIENKHOA,
        HOCKY = @HOCKY,
        MAMH = @MAMH,
        NHOM = @NHOM,
        MAGV = @MAGV,
        MAKHOA = @MAKHOA,
        SOSVTOITHIEU = @SOSVTOITHIEU
    WHERE MALTC = @MALTC;
END;
GO

CREATE OR ALTER PROCEDURE SP_DELETE_LOPTINCHI
    @MALTC INT
AS
BEGIN
    DELETE FROM LOPTINCHI
    WHERE MALTC = @MALTC;
END;
GO

CREATE OR ALTER PROCEDURE SP_CANCEL_LOPTINCHI
    @MALTC INT
AS
BEGIN
    UPDATE LOPTINCHI
    SET HUYLOP = 1
    WHERE MALTC = @MALTC;
END;
GO

CREATE OR ALTER PROCEDURE SP_RESTORE_LOPTINCHI
    @MALTC INT
AS
BEGIN
    UPDATE LOPTINCHI
    SET HUYLOP = 0
    WHERE MALTC = @MALTC;
END;
GO

CREATE OR ALTER PROCEDURE SP_SEARCH_LOPTINCHI
    @KEYWORD NVARCHAR(100)
AS
BEGIN
    SELECT ltc.MALTC, ltc.NIENKHOA, ltc.HOCKY, ltc.MAMH, ltc.NHOM, ltc.MAGV, ltc.MAKHOA, ltc.SOSVTOITHIEU, ltc.HUYLOP
    FROM LOPTINCHI ltc
    INNER JOIN MONHOC mh ON ltc.MAMH = mh.MAMH
    INNER JOIN GIANGVIEN gv ON ltc.MAGV = gv.MAGV
    WHERE (ltc.NIENKHOA LIKE '%' + @KEYWORD + '%' 
       OR mh.TENMH LIKE '%' + @KEYWORD + '%'
       OR gv.HO + ' ' + gv.TEN LIKE '%' + @KEYWORD + '%');
END;
GO


-- =========================================================================
-- 7. STORED PROCEDURES - DANGKY
-- =========================================================================

CREATE OR ALTER PROCEDURE SP_GET_ALL_DANGKY
AS
BEGIN
    SELECT MALTC, MASV, DIEM_CC, DIEM_GK, DIEM_CK, HUYDANGKY
    FROM DANGKY;
END;
GO

CREATE OR ALTER PROCEDURE SP_GET_DANGKY_BY_LOPTINCHI
    @MALTC INT
AS
BEGIN
    SELECT MALTC, MASV, DIEM_CC, DIEM_GK, DIEM_CK, HUYDANGKY
    FROM DANGKY
    WHERE MALTC = @MALTC AND HUYDANGKY = 0;
END;
GO

CREATE OR ALTER PROCEDURE SP_GET_DANGKY_BY_SINHVIEN
    @MASV NCHAR(10)
AS
BEGIN
    SELECT 
        dk.MALTC, 
        dk.MASV, 
        dk.DIEM_CC, 
        dk.DIEM_GK, 
        dk.DIEM_CK, 
        dk.HUYDANGKY,
        ltc.MAMH,
        mh.TENMH,
        ltc.NHOM,
        ltc.MAGV,
        gv.HO + ' ' + gv.TEN AS TENGV,
        ltc.NIENKHOA,
        ltc.HOCKY
    FROM DANGKY dk
    INNER JOIN LOPTINCHI ltc ON dk.MALTC = ltc.MALTC
    INNER JOIN MONHOC mh ON ltc.MAMH = mh.MAMH
    INNER JOIN GIANGVIEN gv ON ltc.MAGV = gv.MAGV
    WHERE dk.MASV = @MASV AND (dk.HUYDANGKY = 0 OR dk.HUYDANGKY IS NULL);
END;
GO

CREATE OR ALTER PROCEDURE SP_CREATE_DANGKY
    @MALTC INT,
    @MASV NCHAR(10),
    @DIEM_CC INT,
    @DIEM_GK FLOAT,
    @DIEM_CK FLOAT,
    @HUYDANGKY BIT
AS
BEGIN
    -- MERGE: Upsert 1 pass duy nhất thay vì IF EXISTS (2 lần quét bảng)
    MERGE DANGKY AS target
    USING (SELECT @MALTC, @MASV) AS source (MALTC, MASV)
      ON target.MALTC = source.MALTC AND target.MASV = source.MASV
    WHEN MATCHED THEN
        UPDATE SET HUYDANGKY = @HUYDANGKY,
                   DIEM_CC = @DIEM_CC,
                   DIEM_GK = @DIEM_GK,
                   DIEM_CK = @DIEM_CK
    WHEN NOT MATCHED THEN
        INSERT (MALTC, MASV, DIEM_CC, DIEM_GK, DIEM_CK, HUYDANGKY)
        VALUES (@MALTC, @MASV, @DIEM_CC, @DIEM_GK, @DIEM_CK, @HUYDANGKY);
END;
GO

CREATE OR ALTER PROCEDURE SP_UPDATE_DANGKY
    @MALTC INT,
    @MASV NCHAR(10),
    @DIEM_CC INT,
    @DIEM_GK FLOAT,
    @DIEM_CK FLOAT,
    @HUYDANGKY BIT
AS
BEGIN
    UPDATE DANGKY
    SET DIEM_CC = @DIEM_CC,
        DIEM_GK = @DIEM_GK,
        DIEM_CK = @DIEM_CK,
        HUYDANGKY = @HUYDANGKY
    WHERE MALTC = @MALTC AND MASV = @MASV;
END;
GO

CREATE OR ALTER PROCEDURE SP_DELETE_DANGKY
    @MALTC INT,
    @MASV NCHAR(10)
AS
BEGIN
    DELETE FROM DANGKY
    WHERE MALTC = @MALTC AND MASV = @MASV;
END;
GO

CREATE OR ALTER PROCEDURE SP_CANCEL_DANGKY
    @MALTC INT,
    @MASV NCHAR(10)
AS
BEGIN
    UPDATE DANGKY
    SET HUYDANGKY = 1
    WHERE MALTC = @MALTC AND MASV = @MASV;
END;
GO

CREATE OR ALTER PROCEDURE SP_RESTORE_DANGKY
    @MALTC INT,
    @MASV NCHAR(10)
AS
BEGIN
    UPDATE DANGKY
    SET HUYDANGKY = 0
    WHERE MALTC = @MALTC AND MASV = @MASV;
END;
GO


-- =========================================================================
-- 8. STORED PROCEDURES - DIEM & REPORTS
-- =========================================================================

-- Lấy bảng điểm theo lớp tín chỉ
CREATE OR ALTER PROCEDURE SP_GET_DIEM_BY_LOPTINCHI
    @MALTC INT
AS
BEGIN
    SELECT dk.MALTC, dk.MASV, sv.HO, sv.TEN, dk.DIEM_CC, dk.DIEM_GK, dk.DIEM_CK
    FROM DANGKY dk
    INNER JOIN SINHVIEN sv ON dk.MASV = sv.MASV
    WHERE dk.MALTC = @MALTC AND dk.HUYDANGKY = 0;
END;
GO

-- Lấy bảng điểm theo sinh viên
CREATE OR ALTER PROCEDURE SP_GET_DIEM_BY_SINHVIEN
    @MASV NCHAR(10)
AS
BEGIN
    ;WITH FilteredDangKy AS (
        SELECT MALTC, DIEM_CC, DIEM_GK, DIEM_CK
        FROM DANGKY
        WHERE MASV = @MASV AND HUYDANGKY = 0
    )
    SELECT dk.MALTC, ltc.MAMH, mh.TENMH, ltc.NHOM, dk.DIEM_CC, dk.DIEM_GK, dk.DIEM_CK
    FROM FilteredDangKy dk
    INNER JOIN LOPTINCHI ltc ON dk.MALTC = ltc.MALTC
    INNER JOIN MONHOC mh ON ltc.MAMH = mh.MAMH;
END;
GO

-- Cập nhật điểm cho 1 sinh viên
CREATE OR ALTER PROCEDURE SP_UPDATE_DIEM
    @MALTC INT,
    @MASV NCHAR(10),
    @DIEM_CC INT,
    @DIEM_GK FLOAT,
    @DIEM_CK FLOAT
AS
BEGIN
    UPDATE DANGKY
    SET DIEM_CC = @DIEM_CC,
        DIEM_GK = @DIEM_GK,
        DIEM_CK = @DIEM_CK
    WHERE MALTC = @MALTC AND MASV = @MASV;
END;
GO

-- Cập nhật điểm hàng loạt cho lớp tín chỉ bằng cách truyền chuỗi JSON
CREATE OR ALTER PROCEDURE SP_UPDATE_DIEM_BATCH
    @MALTC INT,
    @JSON_DATA NVARCHAR(MAX)
AS
BEGIN
    UPDATE dk
    SET dk.DIEM_CC = jd.DIEM_CC,
        dk.DIEM_GK = jd.DIEM_GK,
        dk.DIEM_CK = jd.DIEM_CK
    FROM DANGKY dk
    INNER JOIN OPENJSON(@JSON_DATA)
    WITH (
        MASV NCHAR(10) '$.MASV',
        DIEM_CC INT '$.DIEM_CC',
        DIEM_GK FLOAT '$.DIEM_GK',
        DIEM_CK FLOAT '$.DIEM_CK'
    ) jd ON dk.MASV = jd.MASV
    WHERE dk.MALTC = @MALTC AND dk.HUYDANGKY = 0;
END;
GO

-- BÁO CÁO: Bảng điểm môn học theo lớp tín chỉ
CREATE OR ALTER PROCEDURE SP_REPORT_BANGDIEM_MONHOC
    @MALTC INT
AS
BEGIN
    SELECT 
        dk.MASV,
        sv.HO,
        sv.TEN,
        dk.DIEM_CC,
        dk.DIEM_GK,
        dk.DIEM_CK,
        (ISNULL(dk.DIEM_CC, 0) * 0.1 + ISNULL(dk.DIEM_GK, 0) * 0.3 + ISNULL(dk.DIEM_CK, 0) * 0.6) AS DIEM_KTHP
    FROM DANGKY dk
    INNER JOIN SINHVIEN sv ON dk.MASV = sv.MASV
    WHERE dk.MALTC = @MALTC AND dk.HUYDANGKY = 0
    ORDER BY sv.TEN, sv.HO;
END;
GO

CREATE OR ALTER PROCEDURE SP_REPORT_PHIEUDIEM
    @MASV NCHAR(10)
AS
BEGIN
    ;WITH FilteredDangKy AS (
        SELECT MALTC, DIEM_CC, DIEM_GK, DIEM_CK
        FROM DANGKY
        WHERE MASV = @MASV AND (HUYDANGKY = 0 OR HUYDANGKY IS NULL)
    ),
    ScoreBySubject AS (
        SELECT
            mh.MAMH,
            mh.TENMH,
            dk.DIEM_CC,
            dk.DIEM_GK,
            dk.DIEM_CK,
            CASE 
                WHEN dk.DIEM_CK IS NULL THEN NULL  -- Chưa nhập điểm -> không tính
                ELSE ISNULL(dk.DIEM_CC, 0) * 0.1 + ISNULL(dk.DIEM_GK, 0) * 0.3 + dk.DIEM_CK * 0.6
            END AS DIEM,
            ltc.NIENKHOA,
            ltc.HOCKY,
            ROW_NUMBER() OVER (
                PARTITION BY mh.MAMH 
                ORDER BY 
                    CASE WHEN dk.DIEM_CK IS NULL THEN 0 ELSE 1 END DESC,
                    CASE 
                        WHEN dk.DIEM_CK IS NULL THEN NULL
                        ELSE ISNULL(dk.DIEM_CC, 0) * 0.1 + ISNULL(dk.DIEM_GK, 0) * 0.3 + dk.DIEM_CK * 0.6
                    END DESC,
                    ltc.NIENKHOA DESC,
                    ltc.HOCKY DESC
            ) AS rn
        FROM FilteredDangKy dk
        INNER JOIN LOPTINCHI ltc ON dk.MALTC = ltc.MALTC
        INNER JOIN MONHOC mh ON ltc.MAMH = mh.MAMH
    )
    SELECT
        ROW_NUMBER() OVER (ORDER BY TENMH) AS STT,
        TENMH,
        DIEM_CC,
        DIEM_GK,
        DIEM_CK,
        DIEM,
        NIENKHOA,
        HOCKY
    FROM ScoreBySubject
    WHERE rn = 1
    ORDER BY TENMH;
END;
GO


-- BÁO CÁO: Bảng điểm tổng kết theo lớp (Dynamic Pivot)
-- BÁO CÁO: Bảng điểm tổng kết theo lớp (Dynamic Pivot + Bảng tạm)
-- BÁO CÁO: Bảng điểm tổng kết theo lớp (Dynamic Pivot + Bảng tạm)
CREATE OR ALTER PROCEDURE SP_REPORT_BANGDIEM_TONGKET
    @MALOP NCHAR(10)
AS
BEGIN
    -- ===== BẢNG TẠM: Gom dữ liệu điểm thô, chỉ lấy SV có đăng ký =====
    -- Dùng INNER JOIN thay vì LEFT JOIN để tránh phình bảng tạm với NULL rows
    SELECT 
        sv.MASV,
        sv.HO,
        sv.TEN,
        mh.TENMH,
        CASE 
            WHEN dk.DIEM_CK IS NULL THEN NULL
            ELSE ISNULL(dk.DIEM_CC, 0) * 0.1 + ISNULL(dk.DIEM_GK, 0) * 0.3 + dk.DIEM_CK * 0.6
        END AS DIEM_KTHP
    INTO #DiemRaw
    FROM SINHVIEN sv
    INNER JOIN DANGKY dk ON sv.MASV = dk.MASV AND dk.HUYDANGKY = 0
    INNER JOIN LOPTINCHI ltc ON dk.MALTC = ltc.MALTC
    INNER JOIN MONHOC mh ON ltc.MAMH = mh.MAMH
    WHERE sv.MALOP = @MALOP;

    -- Tạo index giúp PIVOT đọc nhanh theo TENMH
    CREATE NONCLUSTERED INDEX IX_DiemRaw_TENMH ON #DiemRaw (TENMH) INCLUDE (MASV, HO, TEN, DIEM_KTHP);

    -- Lấy danh sách tên môn học từ bảng tạm
    DECLARE @cols AS NVARCHAR(MAX),
            @query AS NVARCHAR(MAX);

    SELECT @cols = COALESCE(@cols + ', ', '') + QUOTENAME(TENMH)
    FROM (SELECT DISTINCT TENMH FROM #DiemRaw WHERE TENMH IS NOT NULL) AS Subjects;

    IF @cols IS NULL OR @cols = ''
    BEGIN
        -- Trả về danh sách sinh viên cơ bản nếu chưa có đăng ký môn nào
        SELECT DISTINCT MASV, HO, TEN 
        FROM SINHVIEN 
        WHERE MALOP = @MALOP;
        DROP TABLE #DiemRaw;
        RETURN;
    END

    -- PIVOT chỉ trên bảng tạm nhỏ - không cần JOIN lại 4 bảng lớn
    SET @query = N'
    SELECT MASV, HO, TEN, ' + @cols + N'
    FROM #DiemRaw
    PIVOT (
        MAX(DIEM_KTHP)
        FOR TENMH IN (' + @cols + N')
    ) piv;'

    EXEC sp_executesql @query;

    DROP TABLE #DiemRaw;
END;
GO

-- BÁO CÁO: Danh sách sinh viên đăng ký lớp tín chỉ
CREATE OR ALTER PROCEDURE SP_REPORT_DSSV_DANGKY
    @MALTC INT
AS
BEGIN
    SELECT 
        sv.MASV,
        sv.HO,
        sv.TEN,
        sv.PHAI,
        sv.MALOP
    FROM DANGKY dk
    INNER JOIN SINHVIEN sv ON dk.MASV = sv.MASV
    WHERE dk.MALTC = @MALTC AND dk.HUYDANGKY = 0
    ORDER BY sv.TEN, sv.HO;
END;
GO

-- BÁO CÁO: Danh sách lớp tín chỉ của niên khoá + học kỳ
-- BÁO CÁO: Danh sách lớp tín chỉ của niên khoá + học kỳ (Bảng tạm)
-- BÁO CÁO: Danh sách lớp tín chỉ của niên khoá + học kỳ (Bảng tạm)
CREATE OR ALTER PROCEDURE SP_REPORT_DS_LOPTINCHI
    @NIENKHOA NCHAR(9),
    @HOCKY INT
AS
BEGIN
    SET NOCOUNT ON; -- Tối ưu băng thông mạng

    -- BƯỚC 1: Gom nhóm, lọc active và đếm sĩ số ném thẳng vào bảng tạm vật lý
    SELECT 
        dk_sub.MALTC, 
        COUNT(dk_sub.MASV) AS SOSV_DANGKY
    INTO #ThongKeDangKy
    FROM DANGKY dk_sub
    WHERE dk_sub.HUYDANGKY = 0 OR dk_sub.HUYDANGKY IS NULL
    GROUP BY dk_sub.MALTC;

    -- BƯỚC 2: "Vả" Clustered Index trực tiếp trên bảng tạm để phép LEFT JOIN phía dưới chạy bằng INDEX SEEK
    CREATE CLUSTERED INDEX IX_Temp_ThongKeDangKy_MALTC ON #ThongKeDangKy(MALTC);

    -- BƯỚC 3: Câu lệnh chính - JOIN các bảng danh mục mục tiêu với bảng tạm sạch
    SELECT 
        ltc.MALTC,
        mh.TENMH,
        ltc.NHOM,
        gv.HO + ' ' + gv.TEN AS HOTEN_GV,
        ltc.SOSVTOITHIEU,
        ISNULL(tk.SOSV_DANGKY, 0) AS SOSV_DANGKY -- Nếu lớp trống (không khớp bảng tạm) thì hiện số 0
    FROM LOPTINCHI ltc
    INNER JOIN MONHOC mh ON ltc.MAMH = mh.MAMH
    INNER JOIN GIANGVIEN gv ON ltc.MAGV = gv.MAGV
    -- LEFT JOIN với bảng tạm siêu nhỏ đã có sẵn Index
    LEFT JOIN #ThongKeDangKy tk ON ltc.MALTC = tk.MALTC
    WHERE ltc.NIENKHOA = @NIENKHOA 
      AND ltc.HOCKY = @HOCKY 
      AND ltc.HUYLOP = 0
    ORDER BY mh.TENMH, ltc.NHOM;

    -- BƯỚC 4: Xóa bảng tạm để dọn dẹp sạch sẽ tài nguyên vùng tempdb
    DROP TABLE #ThongKeDangKy;
END;
GO

-- =========================================================================
-- 9. STORED PROCEDURES - DASHBOARD (ADDITIONAL)
-- =========================================================================

CREATE OR ALTER PROCEDURE SP_DASHBOARD_GET_FILTERS
AS
BEGIN
    -- Recordset 0: Danh sách Khoa
    SELECT MAKHOA, TENKHOA FROM KHOA;
    
    -- Recordset 1: Danh sách Niên khóa, Học kỳ từ Lớp tín chỉ
    SELECT DISTINCT NIENKHOA, HOCKY FROM LOPTINCHI;
END;
GO

CREATE OR ALTER PROCEDURE SP_DASHBOARD_GET_STATS
    @MAKHOA NCHAR(10) = NULL,
    @NIENKHOA NCHAR(9) = NULL,
    @HOCKY INT = NULL
AS
BEGIN
    -- ===== BẢNG TẠM 1: Lọc LOPTINCHI 1 lần duy nhất =====
    SELECT MALTC, MAMH, NHOM, MAGV, SOSVTOITHIEU, HUYLOP
    INTO #FilteredLopTinChi
    FROM LOPTINCHI
    WHERE (@MAKHOA IS NULL OR MAKHOA = @MAKHOA)
      AND (@NIENKHOA IS NULL OR NIENKHOA = @NIENKHOA)
      AND (@HOCKY IS NULL OR HOCKY = @HOCKY);

    ALTER TABLE #FilteredLopTinChi ADD CONSTRAINT PK_FilteredLTC PRIMARY KEY CLUSTERED (MALTC);

    -- ===== BẢNG TẠM 2: Đếm số SV đăng ký 1 lần, dùng chung cho cả 2 Recordset =====
    SELECT fltc.MALTC, COUNT(dk.MASV) AS SOSVDANGKY
    INTO #DangKyCount
    FROM #FilteredLopTinChi fltc
    LEFT JOIN DANGKY dk ON dk.MALTC = fltc.MALTC AND dk.HUYDANGKY = 0
    GROUP BY fltc.MALTC;

    ALTER TABLE #DangKyCount ADD CONSTRAINT PK_DKCount PRIMARY KEY CLUSTERED (MALTC);

    -- Recordset 0: Thống kê tổng quan
    DECLARE @TotalStudents INT;
    DECLARE @OpenClasses INT;
    DECLARE @TotalClasses INT;
    DECLARE @TotalRegistrations INT;

    SELECT @TotalStudents = COUNT(sv.MASV)
    FROM SINHVIEN sv
    INNER JOIN LOP l ON sv.MALOP = l.MALOP
    WHERE (@MAKHOA IS NULL OR l.MAKHOA = @MAKHOA);

    SELECT
        @OpenClasses = SUM(CASE WHEN fltc.HUYLOP = 0 THEN 1 ELSE 0 END),
        @TotalClasses = COUNT(*),
        @TotalRegistrations = SUM(dkc.SOSVDANGKY)
    FROM #FilteredLopTinChi fltc
    INNER JOIN #DangKyCount dkc ON dkc.MALTC = fltc.MALTC;

    SELECT @TotalStudents AS TotalStudents,
           @OpenClasses AS OpenClasses,
           @TotalClasses AS TotalClasses,
           @TotalRegistrations AS TotalRegistrations;

    -- Recordset 1: Chi tiết các lớp tín chỉ (dùng lại cả 2 bảng tạm)
    SELECT 
        ltc.MALTC,
        mh.TENMH,
        ltc.NHOM,
        gv.HO + ' ' + gv.TEN AS TEN_GV,
        ltc.SOSVTOITHIEU,
        ISNULL(dkc.SOSVDANGKY, 0) AS SOSVDANGKY
    FROM #FilteredLopTinChi ltc
    INNER JOIN MONHOC mh ON ltc.MAMH = mh.MAMH
    INNER JOIN GIANGVIEN gv ON ltc.MAGV = gv.MAGV
    LEFT JOIN #DangKyCount dkc ON dkc.MALTC = ltc.MALTC
    ORDER BY ltc.MALTC DESC;

    DROP TABLE #DangKyCount;
    DROP TABLE #FilteredLopTinChi;
END;
GO
