USE master;
GO

IF NOT EXISTS (SELECT 1 FROM sys.server_principals WHERE name = 'login_pgv')
BEGIN
    CREATE LOGIN login_pgv WITH PASSWORD = '123', CHECK_POLICY = OFF;
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.server_principals WHERE name = 'login_khoa')
BEGIN
    CREATE LOGIN login_khoa WITH PASSWORD = '123', CHECK_POLICY = OFF;
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.server_principals WHERE name = 'login_sv')
BEGIN
    CREATE LOGIN login_sv WITH PASSWORD = '123456', CHECK_POLICY = OFF;
END;
GO

USE QLDSV_HTC;
GO

IF DATABASE_PRINCIPAL_ID('login_pgv') IS NULL
BEGIN
    CREATE USER login_pgv FOR LOGIN login_pgv;
END;
GO

IF DATABASE_PRINCIPAL_ID('login_khoa') IS NULL
BEGIN
    CREATE USER login_khoa FOR LOGIN login_khoa;
END;
GO

IF DATABASE_PRINCIPAL_ID('login_sv') IS NULL
BEGIN
    CREATE USER login_sv FOR LOGIN login_sv;
END;
GO

IF DATABASE_PRINCIPAL_ID('PGV') IS NULL
BEGIN
    CREATE ROLE PGV;
END;
GO

IF DATABASE_PRINCIPAL_ID('KHOA') IS NULL
BEGIN
    CREATE ROLE KHOA;
END;
GO

IF DATABASE_PRINCIPAL_ID('SV') IS NULL
BEGIN
    CREATE ROLE SV;
END;
GO

IF IS_ROLEMEMBER('PGV', 'login_pgv') = 0
BEGIN
    ALTER ROLE PGV ADD MEMBER login_pgv;
END;
GO

IF IS_ROLEMEMBER('KHOA', 'login_khoa') = 0
BEGIN
    ALTER ROLE KHOA ADD MEMBER login_khoa;
END;
GO

IF IS_ROLEMEMBER('SV', 'login_sv') = 0
BEGIN
    ALTER ROLE SV ADD MEMBER login_sv;
END;
GO

-- phan quyen phong giao vu 
IF IS_ROLEMEMBER('db_owner', 'login_pgv') = 0
BEGIN
    ALTER ROLE db_owner ADD MEMBER login_pgv;
END;
GO

/* =========================
   PHÂN QUYỀN ROLE KHOA
   ========================= */

/* Bảng KHOA */
GRANT SELECT ON dbo.KHOA (MAKHOA, TENKHOA) TO KHOA;
GO
DENY INSERT, UPDATE, DELETE ON dbo.KHOA TO KHOA;
GO

/* Bảng LOP */
GRANT SELECT ON dbo.LOP (MALOP, TENLOP, KHOAHOC, MAKHOA) TO KHOA;
GO
DENY INSERT, UPDATE, DELETE ON dbo.LOP TO KHOA;
GO

/* Bảng SINHVIEN */
GRANT SELECT ON dbo.SINHVIEN (MASV, HO, TEN, MALOP, PHAI, NGAYSINH, DIACHI, DANGHIHOC) TO KHOA;
GO
DENY SELECT ON dbo.SINHVIEN ([PASSWORD]) TO KHOA;
GO
DENY INSERT, UPDATE, DELETE ON dbo.SINHVIEN TO KHOA;
GO

/* Bảng GIANGVIEN */
GRANT SELECT ON dbo.GIANGVIEN (MAGV, HO, TEN, HOCVI, HOCHAM, CHUYENMON, MAKHOA) TO KHOA;
GO
DENY INSERT, UPDATE, DELETE ON dbo.GIANGVIEN TO KHOA;
GO

/* Bảng MONHOC */
GRANT SELECT ON dbo.MONHOC (MAMH, TENMH, SOTIET_LT, SOTIET_TH) TO KHOA;
GO
DENY INSERT, UPDATE, DELETE ON dbo.MONHOC TO KHOA;
GO

/* Bảng LOPTINCHI */
GRANT SELECT ON dbo.LOPTINCHI (MALTC, NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP) TO KHOA;
GO
DENY INSERT, UPDATE, DELETE ON dbo.LOPTINCHI TO KHOA;
GO

/* Bảng DANGKY */
GRANT SELECT ON dbo.DANGKY (MALTC, MASV, DIEM_CC, DIEM_GK, DIEM_CK, HUYDANGKY) TO KHOA;
GO
DENY INSERT ON dbo.DANGKY TO KHOA;
GO
DENY DELETE ON dbo.DANGKY TO KHOA;
GO
GRANT UPDATE ON dbo.DANGKY (DIEM_CC, DIEM_GK, DIEM_CK) TO KHOA;
GO
DENY UPDATE ON dbo.DANGKY (MALTC, MASV, HUYDANGKY) TO KHOA;
GO

/* ==================================================
   PHÂN QUYỀN BẢNG KHOA - ROLE SV
   ================================================== */
GRANT SELECT ON dbo.KHOA (MAKHOA, TENKHOA) TO SV;
GO
DENY INSERT, UPDATE, DELETE ON dbo.KHOA TO SV;
GO

/* Bảng LOP */
GRANT SELECT ON dbo.LOP (MALOP, TENLOP, KHOAHOC, MAKHOA) TO SV;
GO
DENY INSERT, UPDATE, DELETE ON dbo.LOP TO SV;
GO

/* Bảng SINHVIEN */
GRANT SELECT ON dbo.SINHVIEN (MASV, HO, TEN, MALOP, PHAI, NGAYSINH, DIACHI) TO SV;
GO
DENY SELECT ON dbo.SINHVIEN (DANGHIHOC, [PASSWORD]) TO SV;
GO
DENY INSERT, UPDATE, DELETE ON dbo.SINHVIEN TO SV;
GO

/* Bảng GIANGVIEN */
GRANT SELECT ON dbo.GIANGVIEN (MAGV, HO, TEN, HOCVI, HOCHAM, CHUYENMON, MAKHOA) TO SV;
GO
DENY INSERT, UPDATE, DELETE ON dbo.GIANGVIEN TO SV;
GO

/* Bảng MONHOC */
GRANT SELECT ON dbo.MONHOC (MAMH, TENMH, SOTIET_LT, SOTIET_TH) TO SV;
GO
DENY INSERT, UPDATE, DELETE ON dbo.MONHOC TO SV;
GO

/* Bảng LOPTINCHI */
GRANT SELECT ON dbo.LOPTINCHI (MALTC, NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP) TO SV;
GO
DENY INSERT, UPDATE, DELETE ON dbo.LOPTINCHI TO SV;
GO

/* Bảng DANGKY */
GRANT SELECT ON dbo.DANGKY (MALTC, MASV, DIEM_CC, DIEM_GK, DIEM_CK, HUYDANGKY) TO SV;
GO
GRANT INSERT ON dbo.DANGKY TO SV;
GO
GRANT UPDATE ON dbo.DANGKY (HUYDANGKY) TO SV;
GO
DENY UPDATE ON dbo.DANGKY (DIEM_CC, DIEM_GK, DIEM_CK) TO SV;
GO
DENY UPDATE ON dbo.DANGKY (MALTC, MASV) TO SV;
GO
DENY DELETE ON dbo.DANGKY TO SV;
GO
