USE [QLDSV_HTC];
GO

-- =========================================================================
-- STORED PROCEDURES - KHOA
-- =========================================================================

CREATE OR ALTER PROCEDURE SP_GET_ALL_KHOA
AS
BEGIN
    SELECT MAKHOA, TENKHOA 
    FROM KHOA;
END;
GO

CREATE OR ALTER PROCEDURE SP_GET_KHOA_BY_ID
    @MAKHOA NCHAR(10)
AS
BEGIN
    SELECT MAKHOA, TENKHOA 
    FROM KHOA 
    WHERE MAKHOA = @MAKHOA;
END;
GO

CREATE OR ALTER PROCEDURE SP_CREATE_KHOA
    @MAKHOA NCHAR(10),
    @TENKHOA NVARCHAR(50)
AS
BEGIN
    INSERT INTO KHOA (MAKHOA, TENKHOA)
    VALUES (@MAKHOA, @TENKHOA);
END;
GO

CREATE OR ALTER PROCEDURE SP_UPDATE_KHOA
    @MAKHOA NCHAR(10),
    @TENKHOA NVARCHAR(50)
AS
BEGIN
    UPDATE KHOA
    SET TENKHOA = @TENKHOA
    WHERE MAKHOA = @MAKHOA;
END;
GO

CREATE OR ALTER PROCEDURE SP_DELETE_KHOA
    @MAKHOA NCHAR(10)
AS
BEGIN
    DELETE FROM KHOA
    WHERE MAKHOA = @MAKHOA;
END;
GO

CREATE OR ALTER PROCEDURE SP_RESTORE_KHOA
    @MAKHOA NCHAR(10)
AS
BEGIN
    -- No-op: KHOA table doesn't have Daxoa in your schema
    SELECT 1;
END;
GO

CREATE OR ALTER PROCEDURE SP_SEARCH_KHOA
    @KEYWORD NVARCHAR(100)
AS
BEGIN
    SELECT MAKHOA, TENKHOA
    FROM KHOA
    WHERE MAKHOA LIKE '%' + @KEYWORD + '%' OR TENKHOA LIKE '%' + @KEYWORD + '%';
END;
GO
