USE [QLDSV_HTC];
GO

-- =========================================================================
-- SUPPORTING INDEXES - PGV (LOP, GIANGVIEN, LOPTINCHI, DANGKY)
-- =========================================================================

IF OBJECT_ID('dbo.IX_LOP_MAKHOA', 'IX') IS NULL
BEGIN
    CREATE INDEX IX_LOP_MAKHOA
    ON dbo.LOP (MAKHOA)
    INCLUDE (MALOP, TENLOP, KHOAHOC);
END;
GO

IF OBJECT_ID('dbo.IX_GIANGVIEN_MAKHOA', 'IX') IS NULL
BEGIN
    CREATE INDEX IX_GIANGVIEN_MAKHOA
    ON dbo.GIANGVIEN (MAKHOA)
    INCLUDE (MAGV, HO, TEN, HOCVI, HOCHAM, CHUYENMON);
END;
GO

IF OBJECT_ID('dbo.IX_LOPTINCHI_MAKHOA', 'IX') IS NULL
BEGIN
    CREATE INDEX IX_LOPTINCHI_MAKHOA
    ON dbo.LOPTINCHI (MAKHOA)
    INCLUDE (MALTC, NIENKHOA, HOCKY, MAMH, NHOM, MAGV, SOSVTOITHIEU, HUYLOP);
END;
GO

IF OBJECT_ID('dbo.IX_LOPTINCHI_MAGV', 'IX') IS NULL
BEGIN
    CREATE INDEX IX_LOPTINCHI_MAGV
    ON dbo.LOPTINCHI (MAGV)
    INCLUDE (MALTC, NIENKHOA, HOCKY, MAMH, NHOM, MAKHOA, SOSVTOITHIEU, HUYLOP);
END;
GO

IF OBJECT_ID('dbo.IX_LOPTINCHI_NIENKHOA_HOCKY', 'IX') IS NULL
BEGIN
    CREATE INDEX IX_LOPTINCHI_NIENKHOA_HOCKY
    ON dbo.LOPTINCHI (NIENKHOA, HOCKY)
    INCLUDE (MALTC, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP);
END;
GO


IF OBJECT_ID('dbo.IX_DANGKY_MASV', 'IX') IS NULL
BEGIN
    CREATE INDEX IX_DANGKY_MASV
    ON dbo.DANGKY (MASV)
    INCLUDE (MALTC, DIEM_CC, DIEM_GK, DIEM_CK, HUYDANGKY);
END;
GO

IF OBJECT_ID('dbo.IX_DANGKY_MALTC_HUYDANGKY', 'IX') IS NULL
BEGIN
    -- Index lọc HUYDANGKY=0 theo MALTC - giúp các SP lọc đăng ký active seek nhanh
    CREATE INDEX IX_DANGKY_MALTC_HUYDANGKY
    ON dbo.DANGKY (MALTC, HUYDANGKY)
    INCLUDE (MASV, DIEM_CC, DIEM_GK, DIEM_CK);
END;
GO

-- =========================================================================
-- STORED PROCEDURES - LOP
-- =========================================================================

CREATE OR ALTER PROCEDURE SP_GET_ALL_LOP
AS
BEGIN
    SELECT MALOP, TENLOP, KHOAHOC, MAKHOA
    FROM LOP;
END;
GO

CREATE OR ALTER PROCEDURE SP_GET_LOP_BY_ID
    @MALOP NCHAR(10)
AS
BEGIN
    SELECT MALOP, TENLOP, KHOAHOC, MAKHOA
    FROM LOP
    WHERE MALOP = @MALOP;
END;
GO

CREATE OR ALTER PROCEDURE SP_GET_LOP_BY_KHOA
    @MAKHOA NCHAR(10)
AS
BEGIN
    SELECT MALOP, TENLOP, KHOAHOC, MAKHOA
    FROM LOP
    WHERE MAKHOA = @MAKHOA;
END;
GO

CREATE OR ALTER PROCEDURE SP_CREATE_LOP
    @MALOP NCHAR(10),
    @TENLOP NVARCHAR(50),
    @KHOAHOC NCHAR(9),
    @MAKHOA NCHAR(10)
AS
BEGIN
    INSERT INTO LOP (MALOP, TENLOP, KHOAHOC, MAKHOA)
    VALUES (@MALOP, @TENLOP, @KHOAHOC, @MAKHOA);
END;
GO

CREATE OR ALTER PROCEDURE SP_UPDATE_LOP
    @MALOP NCHAR(10),
    @TENLOP NVARCHAR(50),
    @KHOAHOC NCHAR(9),
    @MAKHOA NCHAR(10)
AS
BEGIN
    UPDATE LOP
    SET TENLOP = @TENLOP,
        KHOAHOC = @KHOAHOC,
        MAKHOA = @MAKHOA
    WHERE MALOP = @MALOP;
END;
GO

CREATE OR ALTER PROCEDURE SP_DELETE_LOP
    @MALOP NCHAR(10)
AS
BEGIN
    DELETE FROM LOP
    WHERE MALOP = @MALOP;
END;
GO

CREATE OR ALTER PROCEDURE SP_RESTORE_LOP
    @MALOP NCHAR(10)
AS
BEGIN
    -- No-op
    SELECT 1;
END;
GO

CREATE OR ALTER PROCEDURE SP_SEARCH_LOP
    @KEYWORD NVARCHAR(100)
AS
BEGIN
    SELECT MALOP, TENLOP, KHOAHOC, MAKHOA
    FROM LOP
    WHERE MALOP LIKE '%' + @KEYWORD + '%' OR TENLOP LIKE '%' + @KEYWORD + '%';
END;
GO

-- =========================================================================
-- STORED PROCEDURES - GIANGVIEN
-- =========================================================================

CREATE OR ALTER PROCEDURE SP_GET_ALL_GIANGVIEN
AS
BEGIN
    SELECT MAGV, MAKHOA, HO, TEN, HOCVI, HOCHAM, CHUYENMON
    FROM GIANGVIEN;
END;
GO

CREATE OR ALTER PROCEDURE SP_GET_GIANGVIEN_BY_ID
    @MAGV NCHAR(10)
AS
BEGIN
    SELECT MAGV, MAKHOA, HO, TEN, HOCVI, HOCHAM, CHUYENMON
    FROM GIANGVIEN
    WHERE MAGV = @MAGV;
END;
GO

CREATE OR ALTER PROCEDURE SP_GET_GIANGVIEN_BY_KHOA
    @MAKHOA NCHAR(10)
AS
BEGIN
    SELECT MAGV, MAKHOA, HO, TEN, HOCVI, HOCHAM, CHUYENMON
    FROM GIANGVIEN
    WHERE MAKHOA = @MAKHOA;
END;
GO

CREATE OR ALTER PROCEDURE SP_CREATE_GIANGVIEN
    @MAGV NCHAR(10),
    @MAKHOA NCHAR(10),
    @HO NVARCHAR(50),
    @TEN NVARCHAR(10),
    @HOCVI NVARCHAR(20),
    @HOCHAM NVARCHAR(20),
    @CHUYENMON NVARCHAR(50)
AS
BEGIN
    INSERT INTO GIANGVIEN (MAGV, MAKHOA, HO, TEN, HOCVI, HOCHAM, CHUYENMON)
    VALUES (@MAGV, @MAKHOA, @HO, @TEN, @HOCVI, @HOCHAM, @CHUYENMON);
END;
GO

CREATE OR ALTER PROCEDURE SP_UPDATE_GIANGVIEN
    @MAGV NCHAR(10),
    @MAKHOA NCHAR(10),
    @HO NVARCHAR(50),
    @TEN NVARCHAR(10),
    @HOCVI NVARCHAR(20),
    @HOCHAM NVARCHAR(20),
    @CHUYENMON NVARCHAR(50)
AS
BEGIN
    UPDATE GIANGVIEN
    SET MAKHOA = @MAKHOA,
        HO = @HO,
        TEN = @TEN,
        HOCVI = @HOCVI,
        HOCHAM = @HOCHAM,
        CHUYENMON = @CHUYENMON
    WHERE MAGV = @MAGV;
END;
GO

CREATE OR ALTER PROCEDURE SP_DELETE_GIANGVIEN
    @MAGV NCHAR(10)
AS
BEGIN
    DELETE FROM GIANGVIEN
    WHERE MAGV = @MAGV;
END;
GO

CREATE OR ALTER PROCEDURE SP_RESTORE_GIANGVIEN
    @MAGV NCHAR(10)
AS
BEGIN
    -- No-op
    SELECT 1;
END;
GO

CREATE OR ALTER PROCEDURE SP_SEARCH_GIANGVIEN
    @KEYWORD NVARCHAR(100)
AS
BEGIN
    SELECT MAGV, MAKHOA, HO, TEN, HOCVI, HOCHAM, CHUYENMON
    FROM GIANGVIEN
    WHERE MAGV LIKE '%' + @KEYWORD + '%' 
       OR HO LIKE '%' + @KEYWORD + '%' 
       OR TEN LIKE '%' + @KEYWORD + '%' 
       OR HO + ' ' + TEN LIKE '%' + @KEYWORD + '%';
END;
GO

-- =========================================================================
-- STORED PROCEDURES - MONHOC
-- =========================================================================

CREATE OR ALTER PROCEDURE SP_GET_ALL_MONHOC
AS
BEGIN
    SELECT MAMH, TENMH, SOTIET_LT, SOTIET_TH
    FROM MONHOC;
END;
GO

CREATE OR ALTER PROCEDURE SP_GET_MONHOC_BY_ID
    @MAMH NCHAR(10)
AS
BEGIN
    SELECT MAMH, TENMH, SOTIET_LT, SOTIET_TH
    FROM MONHOC
    WHERE MAMH = @MAMH;
END;
GO

CREATE OR ALTER PROCEDURE SP_CREATE_MONHOC
    @MAMH NCHAR(10),
    @TENMH NVARCHAR(50),
    @SOTIET_LT INT,
    @SOTIET_TH INT
AS
BEGIN
    INSERT INTO MONHOC (MAMH, TENMH, SOTIET_LT, SOTIET_TH)
    VALUES (@MAMH, @TENMH, @SOTIET_LT, @SOTIET_TH);
END;
GO

CREATE OR ALTER PROCEDURE SP_UPDATE_MONHOC
    @MAMH NCHAR(10),
    @TENMH NVARCHAR(50),
    @SOTIET_LT INT,
    @SOTIET_TH INT
AS
BEGIN
    UPDATE MONHOC
    SET TENMH = @TENMH,
        SOTIET_LT = @SOTIET_LT,
        SOTIET_TH = @SOTIET_TH
    WHERE MAMH = @MAMH;
END;
GO

CREATE OR ALTER PROCEDURE SP_DELETE_MONHOC
    @MAMH NCHAR(10)
AS
BEGIN
    DELETE FROM MONHOC
    WHERE MAMH = @MAMH;
END;
GO

CREATE OR ALTER PROCEDURE SP_RESTORE_MONHOC
    @MAMH NCHAR(10)
AS
BEGIN
    -- No-op
    SELECT 1;
END;
GO

CREATE OR ALTER PROCEDURE SP_SEARCH_MONHOC
    @KEYWORD NVARCHAR(100)
AS
BEGIN
    SELECT MAMH, TENMH, SOTIET_LT, SOTIET_TH
    FROM MONHOC
    WHERE MAMH LIKE '%' + @KEYWORD + '%' OR TENMH LIKE '%' + @KEYWORD + '%';
END;
GO

-- =========================================================================
-- STORED PROCEDURES - LOPTINCHI
-- =========================================================================

CREATE OR ALTER PROCEDURE SP_GET_ALL_LOPTINCHI
AS
BEGIN
    SELECT 
        ltc.MALTC, 
        ltc.NIENKHOA, 
        ltc.HOCKY, 
        ltc.MAMH, 
        mh.TENMH,
        ltc.NHOM, 
        ltc.MAGV, 
        gv.HO + ' ' + gv.TEN AS TENGV,
        ltc.MAKHOA, 
        ltc.SOSVTOITHIEU, 
        ltc.HUYLOP
    FROM LOPTINCHI ltc
    INNER JOIN MONHOC mh ON ltc.MAMH = mh.MAMH
    INNER JOIN GIANGVIEN gv ON ltc.MAGV = gv.MAGV;
END;
GO

CREATE OR ALTER PROCEDURE SP_GET_LOPTINCHI_BY_ID
    @MALTC INT
AS
BEGIN
    SELECT MALTC, NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP
    FROM LOPTINCHI
    WHERE MALTC = @MALTC;
END;
GO

CREATE OR ALTER PROCEDURE SP_GET_LOPTINCHI_BY_KHOA
    @MAKHOA NCHAR(10)
AS
BEGIN
    SELECT MALTC, NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP
    FROM LOPTINCHI
    WHERE MAKHOA = @MAKHOA;
END;
GO

CREATE OR ALTER PROCEDURE SP_GET_LOPTINCHI_BY_NIENKHOA_HOCKY
    @NIENKHOA NCHAR(9),
    @HOCKY INT
AS
BEGIN
    SELECT 
        ltc.MALTC, 
        ltc.NIENKHOA, 
        ltc.HOCKY, 
        ltc.MAMH, 
        mh.TENMH,
        ltc.NHOM, 
        ltc.MAGV, 
        gv.HO + ' ' + gv.TEN AS TENGV,
        ltc.MAKHOA, 
        ltc.SOSVTOITHIEU, 
        ltc.HUYLOP
    FROM LOPTINCHI ltc
    INNER JOIN MONHOC mh ON ltc.MAMH = mh.MAMH
    INNER JOIN GIANGVIEN gv ON ltc.MAGV = gv.MAGV
    WHERE ltc.NIENKHOA = @NIENKHOA 
      AND ltc.HOCKY = @HOCKY
      AND ltc.HUYLOP = 0;
END;
GO

CREATE OR ALTER PROCEDURE SP_GET_LOPTINCHI_BY_GIANGVIEN
    @MAGV NCHAR(10)
AS
BEGIN
    SELECT MALTC, NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP
    FROM LOPTINCHI
    WHERE MAGV = @MAGV;
END;
GO

CREATE OR ALTER PROCEDURE SP_CREATE_LOPTINCHI
    @NIENKHOA NCHAR(9),
    @HOCKY INT,
    @MAMH NCHAR(10),
    @NHOM INT,
    @MAGV NCHAR(10),
    @MAKHOA NCHAR(10),
    @SOSVTOITHIEU INT,
    @HUYLOP BIT
AS
BEGIN
    INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP)
    VALUES (@NIENKHOA, @HOCKY, @MAMH, @NHOM, @MAGV, @MAKHOA, @SOSVTOITHIEU, @HUYLOP);
END;
GO

CREATE OR ALTER PROCEDURE SP_UPDATE_LOPTINCHI
    @MALTC INT,
    @NIENKHOA NCHAR(9),
    @HOCKY INT,
    @MAMH NCHAR(10),
    @NHOM INT,
    @MAGV NCHAR(10),
    @MAKHOA NCHAR(10),
    @SOSVTOITHIEU INT
AS
BEGIN
    UPDATE LOPTINCHI
    SET NIENKHOA = @NIENKHOA,
        HOCKY = @HOCKY,
        MAMH = @MAMH,
        NHOM = @NHOM,
        MAGV = @MAGV,
        MAKHOA = @MAKHOA,
        SOSVTOITHIEU = @SOSVTOITHIEU
    WHERE MALTC = @MALTC;
END;
GO

CREATE OR ALTER PROCEDURE SP_DELETE_LOPTINCHI
    @MALTC INT
AS
BEGIN
    DELETE FROM LOPTINCHI
    WHERE MALTC = @MALTC;
END;
GO

CREATE OR ALTER PROCEDURE SP_CANCEL_LOPTINCHI
    @MALTC INT
AS
BEGIN
    UPDATE LOPTINCHI
    SET HUYLOP = 1
    WHERE MALTC = @MALTC;
END;
GO

CREATE OR ALTER PROCEDURE SP_RESTORE_LOPTINCHI
    @MALTC INT
AS
BEGIN
    UPDATE LOPTINCHI
    SET HUYLOP = 0
    WHERE MALTC = @MALTC;
END;
GO

CREATE OR ALTER PROCEDURE SP_SEARCH_LOPTINCHI
    @KEYWORD NVARCHAR(100)
AS
BEGIN
    SELECT ltc.MALTC, ltc.NIENKHOA, ltc.HOCKY, ltc.MAMH, ltc.NHOM, ltc.MAGV, ltc.MAKHOA, ltc.SOSVTOITHIEU, ltc.HUYLOP
    FROM LOPTINCHI ltc
    INNER JOIN MONHOC mh ON ltc.MAMH = mh.MAMH
    INNER JOIN GIANGVIEN gv ON ltc.MAGV = gv.MAGV
    WHERE (ltc.NIENKHOA LIKE '%' + @KEYWORD + '%' 
       OR mh.TENMH LIKE '%' + @KEYWORD + '%'
       OR gv.HO + ' ' + gv.TEN LIKE '%' + @KEYWORD + '%');
END;
GO

-- =========================================================================
-- STORED PROCEDURES - DANGKY
-- =========================================================================

CREATE OR ALTER PROCEDURE SP_GET_ALL_DANGKY
AS
BEGIN
    SELECT MALTC, MASV, DIEM_CC, DIEM_GK, DIEM_CK, HUYDANGKY
    FROM DANGKY;
END;
GO

CREATE OR ALTER PROCEDURE SP_GET_DANGKY_BY_LOPTINCHI
    @MALTC INT
AS
BEGIN
    SELECT MALTC, MASV, DIEM_CC, DIEM_GK, DIEM_CK, HUYDANGKY
    FROM DANGKY
    WHERE MALTC = @MALTC AND HUYDANGKY = 0;
END;
GO

CREATE OR ALTER PROCEDURE SP_GET_DANGKY_BY_SINHVIEN
    @MASV NCHAR(10)
AS
BEGIN
    SELECT 
        dk.MALTC, 
        dk.MASV, 
        dk.DIEM_CC, 
        dk.DIEM_GK, 
        dk.DIEM_CK, 
        dk.HUYDANGKY,
        ltc.MAMH,
        mh.TENMH,
        ltc.NHOM,
        ltc.MAGV,
        gv.HO + ' ' + gv.TEN AS TENGV,
        ltc.NIENKHOA,
        ltc.HOCKY
    FROM DANGKY dk
    INNER JOIN LOPTINCHI ltc ON dk.MALTC = ltc.MALTC
    INNER JOIN MONHOC mh ON ltc.MAMH = mh.MAMH
    INNER JOIN GIANGVIEN gv ON ltc.MAGV = gv.MAGV
    WHERE dk.MASV = @MASV AND (dk.HUYDANGKY = 0 OR dk.HUYDANGKY IS NULL);
END;
GO

CREATE OR ALTER PROCEDURE SP_CREATE_DANGKY
    @MALTC INT,
    @MASV NCHAR(10),
    @DIEM_CC INT,
    @DIEM_GK FLOAT,
    @DIEM_CK FLOAT,
    @HUYDANGKY BIT
AS
BEGIN
    -- MERGE: Upsert 1 pass duy nhất thay vì IF EXISTS (2 lần quét bảng)
    MERGE DANGKY AS target
    USING (SELECT @MALTC, @MASV) AS source (MALTC, MASV)
      ON target.MALTC = source.MALTC AND target.MASV = source.MASV
    WHEN MATCHED THEN
        UPDATE SET HUYDANGKY = @HUYDANGKY,
                   DIEM_CC = @DIEM_CC,
                   DIEM_GK = @DIEM_GK,
                   DIEM_CK = @DIEM_CK
    WHEN NOT MATCHED THEN
        INSERT (MALTC, MASV, DIEM_CC, DIEM_GK, DIEM_CK, HUYDANGKY)
        VALUES (@MALTC, @MASV, @DIEM_CC, @DIEM_GK, @DIEM_CK, @HUYDANGKY);
END;
GO

CREATE OR ALTER PROCEDURE SP_UPDATE_DANGKY
    @MALTC INT,
    @MASV NCHAR(10),
    @DIEM_CC INT,
    @DIEM_GK FLOAT,
    @DIEM_CK FLOAT,
    @HUYDANGKY BIT
AS
BEGIN
    UPDATE DANGKY
    SET DIEM_CC = @DIEM_CC,
        DIEM_GK = @DIEM_GK,
        DIEM_CK = @DIEM_CK,
        HUYDANGKY = @HUYDANGKY
    WHERE MALTC = @MALTC AND MASV = @MASV;
END;
GO

CREATE OR ALTER PROCEDURE SP_DELETE_DANGKY
    @MALTC INT,
    @MASV NCHAR(10)
AS
BEGIN
    DELETE FROM DANGKY
    WHERE MALTC = @MALTC AND MASV = @MASV;
END;
GO

CREATE OR ALTER PROCEDURE SP_CANCEL_DANGKY
    @MALTC INT,
    @MASV NCHAR(10)
AS
BEGIN
    UPDATE DANGKY
    SET HUYDANGKY = 1
    WHERE MALTC = @MALTC AND MASV = @MASV;
END;
GO

CREATE OR ALTER PROCEDURE SP_RESTORE_DANGKY
    @MALTC INT,
    @MASV NCHAR(10)
AS
BEGIN
    UPDATE DANGKY
    SET HUYDANGKY = 0
    WHERE MALTC = @MALTC AND MASV = @MASV;
END;
GO

-- =========================================================================
-- STORED PROCEDURES - DIEM
-- =========================================================================

-- Lấy bảng điểm theo lớp tín chỉ
CREATE OR ALTER PROCEDURE SP_GET_DIEM_BY_LOPTINCHI
    @MALTC INT
AS
BEGIN
    SELECT dk.MALTC, dk.MASV, sv.HO, sv.TEN, dk.DIEM_CC, dk.DIEM_GK, dk.DIEM_CK
    FROM DANGKY dk
    INNER JOIN SINHVIEN sv ON dk.MASV = sv.MASV
    WHERE dk.MALTC = @MALTC AND dk.HUYDANGKY = 0;
END;
GO

-- Lấy bảng điểm theo sinh viên
CREATE OR ALTER PROCEDURE SP_GET_DIEM_BY_SINHVIEN
    @MASV NCHAR(10)
AS
BEGIN
    ;WITH FilteredDangKy AS (
        SELECT MALTC, DIEM_CC, DIEM_GK, DIEM_CK
        FROM DANGKY
        WHERE MASV = @MASV AND HUYDANGKY = 0
    )
    SELECT dk.MALTC, ltc.MAMH, mh.TENMH, ltc.NHOM, dk.DIEM_CC, dk.DIEM_GK, dk.DIEM_CK
    FROM FilteredDangKy dk
    INNER JOIN LOPTINCHI ltc ON dk.MALTC = ltc.MALTC
    INNER JOIN MONHOC mh ON ltc.MAMH = mh.MAMH;
END;
GO

-- Cập nhật điểm cho 1 sinh viên
CREATE OR ALTER PROCEDURE SP_UPDATE_DIEM
    @MALTC INT,
    @MASV NCHAR(10),
    @DIEM_CC INT,
    @DIEM_GK FLOAT,
    @DIEM_CK FLOAT
AS
BEGIN
    UPDATE DANGKY
    SET DIEM_CC = @DIEM_CC,
        DIEM_GK = @DIEM_GK,
        DIEM_CK = @DIEM_CK
    WHERE MALTC = @MALTC AND MASV = @MASV;
END;
GO

-- Cập nhật điểm hàng loạt cho lớp tín chỉ bằng cách truyền chuỗi JSON
CREATE OR ALTER PROCEDURE SP_UPDATE_DIEM_BATCH
    @MALTC INT,
    @JSON_DATA NVARCHAR(MAX)
AS
BEGIN
    UPDATE dk
    SET dk.DIEM_CC = jd.DIEM_CC,
        dk.DIEM_GK = jd.DIEM_GK,
        dk.DIEM_CK = jd.DIEM_CK
    FROM DANGKY dk
    INNER JOIN OPENJSON(@JSON_DATA)
    WITH (
        MASV NCHAR(10) '$.MASV',
        DIEM_CC INT '$.DIEM_CC',
        DIEM_GK FLOAT '$.DIEM_GK',
        DIEM_CK FLOAT '$.DIEM_CK'
    ) jd ON dk.MASV = jd.MASV
    WHERE dk.MALTC = @MALTC AND dk.HUYDANGKY = 0;
END;
GO
