USE [QLDSV_HTC];
GO

-- =========================================================================
-- SUPPORTING INDEXES - SINHVIEN
-- =========================================================================

IF OBJECT_ID('dbo.IX_SINHVIEN_MALOP', 'IX') IS NULL
BEGIN
    CREATE INDEX IX_SINHVIEN_MALOP
    ON dbo.SINHVIEN (MALOP)
    INCLUDE (MASV, HO, TEN, PHAI, NGAYSINH, DIACHI, DANGHIHOC);
END;
GO

IF OBJECT_ID('dbo.IX_SINHVIEN_MASV', 'IX') IS NULL
BEGIN
    CREATE INDEX IX_SINHVIEN_MASV
    ON dbo.SINHVIEN (MASV)
    INCLUDE (HO, TEN, MALOP, PHAI, NGAYSINH, DIACHI, DANGHIHOC);
END;
GO

-- =========================================================================
-- STORED PROCEDURES - SINHVIEN
-- =========================================================================

CREATE OR ALTER PROCEDURE SP_GET_ALL_SINHVIEN
AS
BEGIN
    SELECT MASV, HO, TEN, MALOP, PHAI, NGAYSINH, DIACHI, DANGHIHOC
    FROM SINHVIEN;
END;
GO

CREATE OR ALTER PROCEDURE SP_GET_SINHVIEN_BY_ID
    @MASV NCHAR(10)
AS
BEGIN
    SELECT MASV, HO, TEN, MALOP, PHAI, NGAYSINH, DIACHI, DANGHIHOC
    FROM SINHVIEN
    WHERE MASV = @MASV;
END;
GO

CREATE OR ALTER PROCEDURE SP_GET_SINHVIEN_BY_LOP
    @MALOP NCHAR(10)
AS
BEGIN
    SELECT MASV, HO, TEN, MALOP, PHAI, NGAYSINH, DIACHI, DANGHIHOC
    FROM SINHVIEN
    WHERE MALOP = @MALOP;
END;
GO

CREATE OR ALTER PROCEDURE SP_GET_SINHVIEN_BY_KHOA
    @MAKHOA NCHAR(10)
AS
BEGIN
    SELECT sv.MASV, sv.HO, sv.TEN, sv.MALOP, sv.PHAI, sv.NGAYSINH, sv.DIACHI, sv.DANGHIHOC
    FROM SINHVIEN sv
    INNER JOIN LOP l ON sv.MALOP = l.MALOP
    WHERE l.MAKHOA = @MAKHOA;
END;
GO

CREATE OR ALTER PROCEDURE SP_CREATE_SINHVIEN
    @MASV NCHAR(10),
    @HO NVARCHAR(50),
    @TEN NVARCHAR(10),
    @MALOP NCHAR(10),
    @PHAI BIT,
    @NGAYSINH DATE = NULL,
    @DIACHI NVARCHAR(100) = NULL,
    @DANGHIHOC BIT = 0
AS
BEGIN
    INSERT INTO SINHVIEN (MASV, HO, TEN, MALOP, PHAI, NGAYSINH, DIACHI, DANGHIHOC)
    VALUES (@MASV, @HO, @TEN, @MALOP, @PHAI, @NGAYSINH, @DIACHI, @DANGHIHOC);
END;
GO

CREATE OR ALTER PROCEDURE SP_UPDATE_SINHVIEN
    @MASV NCHAR(10),
    @HO NVARCHAR(50),
    @TEN NVARCHAR(10),
    @MALOP NCHAR(10),
    @PHAI BIT,
    @NGAYSINH DATE = NULL,
    @DIACHI NVARCHAR(100) = NULL,
    @DANGHIHOC BIT = 0
AS
BEGIN
    UPDATE SINHVIEN
    SET HO = @HO,
        TEN = @TEN,
        MALOP = @MALOP,
        PHAI = @PHAI,
        NGAYSINH = @NGAYSINH,
        DIACHI = @DIACHI,
        DANGHIHOC = @DANGHIHOC
    WHERE MASV = @MASV;
END;
GO

CREATE OR ALTER PROCEDURE SP_DELETE_SINHVIEN
    @MASV NCHAR(10)
AS
BEGIN
    DELETE FROM SINHVIEN
    WHERE MASV = @MASV;
END;
GO

CREATE OR ALTER PROCEDURE SP_RESTORE_SINHVIEN
    @MASV NCHAR(10)
AS
BEGIN
    UPDATE SINHVIEN
    SET DANGHIHOC = 0
    WHERE MASV = @MASV;
END;
GO

CREATE OR ALTER PROCEDURE SP_SEARCH_SINHVIEN
    @KEYWORD NVARCHAR(100)
AS
BEGIN
    SELECT MASV, HO, TEN, MALOP, PHAI, NGAYSINH, DIACHI, DANGHIHOC
    FROM SINHVIEN
    WHERE MASV LIKE '%' + @KEYWORD + '%' 
       OR HO LIKE '%' + @KEYWORD + '%' 
       OR TEN LIKE '%' + @KEYWORD + '%' 
       OR HO + ' ' + TEN LIKE '%' + @KEYWORD + '%';
END;
GO

CREATE OR ALTER PROCEDURE SP_UPDATE_SINHVIEN_STATUS
    @MASV NCHAR(10),
    @DANGHIHOC BIT
AS
BEGIN
    UPDATE SINHVIEN
    SET DANGHIHOC = @DANGHIHOC
    WHERE MASV = @MASV;
END;
GO
